<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CsiCodePricesTableSeeder extends Seeder
{

    protected $prices = [
        [
            'building_materials' => null,
            'labor' => 150,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 30,
            'labor' => 70,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 30,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 120,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 50,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 0,
            'subcontractors' => 1500,
        ],
        [
            'building_materials' => null,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.1,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0,
            'labor' => 0.3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.4,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 25,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 25,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 25,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 50,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 45,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 25,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 25,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 30,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 1.6,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 2.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 1.57,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 1.82,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.45,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 1.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.39,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.39,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.59,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.4,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.59,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.6,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.35,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.35,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 1.57,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 4,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 2.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.1,
            'labor' => 1.75,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.1,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 8,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.1,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.8,
            'labor' => 1.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.6,
            'labor' => 1.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.8,
            'labor' => 1.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 1.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.8,
            'labor' => 2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.8,
            'labor' => 2.4,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 3,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 15,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 100,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 40,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 5,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 5,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 5,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 15,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 60,
            'labor' => 50,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 40,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 600,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 300,
        ],
        [
            'building_materials' => 120,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 400,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 250,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 80,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 100,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 1000,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 1200,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 800,
            'subcontractors' => 300,
        ],
        [
            'building_materials' => 50,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 100,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 80,
        ],
        [
            'building_materials' => 200,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 1000,
        ],
        [
            'building_materials' => 50,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 200,
        ],
        [
            'building_materials' => 30,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 80,
        ],
        [
            'building_materials' => 30,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 100,
        ],
        [
            'building_materials' => 15,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 60,
        ],
        [
            'building_materials' => 3,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 60,
        ],
        [
            'building_materials' => 25,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 60,
        ],
        [
            'building_materials' => 10,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 60,
        ],
        [
            'building_materials' => 10,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 30,
        ],
        [
            'building_materials' => 10,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 15,
        ],
        [
            'building_materials' => 0.6,
            'labor' => 0.8,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.6,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.95,
            'labor' => 0.8,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.55,
            'labor' => 0.8,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.1,
            'labor' => 0.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.15,
            'labor' => 0.3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.15,
            'labor' => 0.3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.8,
            'labor' => 1.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 0.6,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.4,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 0.4,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.55,
            'labor' => 0.9,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.1,
            'labor' => 0.23,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.15,
            'labor' => 0.35,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.23,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.8,
            'labor' => 1.8,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 1.7,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 1.48,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 1.48,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 7,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 7,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 7,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 7,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 7,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 7,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.45,
            'labor' => 0.45,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.1,
            'labor' => 0.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.15,
            'labor' => 0.3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.15,
            'labor' => 0.3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.6,
            'labor' => 0.6,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 0.3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 0.4,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 0.3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.9,
            'labor' => 0.15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.1,
            'labor' => 0.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1.25,
            'labor' => 3.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1.25,
            'labor' => 2.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.9,
            'labor' => 1.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.55,
            'labor' => 0.9,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1.5,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1.5,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 10,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.5,
            'labor' => 0.3,
            'manufacturing' => null,
            'decoration_materials' => 9.5,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.5,
            'labor' => 0.3,
            'manufacturing' => null,
            'decoration_materials' => 9.5,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 10,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 182,
            'subcontractors' => 100,
        ],
        [
            'building_materials' => 1,
            'labor' => 2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 1.9,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 1.75,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 4.5,
            'manufacturing' => null,
            'decoration_materials' => 4,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 6,
            'manufacturing' => null,
            'decoration_materials' => 4,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 7,
            'manufacturing' => null,
            'decoration_materials' => 15,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 7,
            'manufacturing' => null,
            'decoration_materials' => 10,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 8,
            'manufacturing' => null,
            'decoration_materials' => 15,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => 15,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => 2,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 4,
            'manufacturing' => null,
            'decoration_materials' => 4,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => 4,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 7,
            'manufacturing' => null,
            'decoration_materials' => 15,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 7,
            'manufacturing' => null,
            'decoration_materials' => 10,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 6,
            'manufacturing' => null,
            'decoration_materials' => 4,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 8,
            'manufacturing' => null,
            'decoration_materials' => 4,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 9,
            'manufacturing' => null,
            'decoration_materials' => 15,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 9,
            'manufacturing' => null,
            'decoration_materials' => 10,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 2,
            'labor' => 12,
            'manufacturing' => null,
            'decoration_materials' => 10,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 20,
            'labor' => 150,
            'manufacturing' => null,
            'decoration_materials' => 130,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 15,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => 25,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 10,
            'labor' => 90,
            'manufacturing' => null,
            'decoration_materials' => 80,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => 6,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => 6,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 20,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => 125,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.5,
            'labor' => 3.5,
            'manufacturing' => null,
            'decoration_materials' => 3,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 3,
            'manufacturing' => null,
            'decoration_materials' => 3,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 3.5,
            'manufacturing' => null,
            'decoration_materials' => 4,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 1.25,
            'manufacturing' => null,
            'decoration_materials' => 1.25,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => 1.25,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => 1.1,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.25,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => 2.25,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 1.8,
            'manufacturing' => null,
            'decoration_materials' => 1.25,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 1.8,
            'manufacturing' => null,
            'decoration_materials' => 3.25,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 1.8,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 1.8,
            'manufacturing' => null,
            'decoration_materials' => 3,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 10,
            'labor' => 30,
            'manufacturing' => null,
            'decoration_materials' => 39,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 3,
            'labor' => 21,
            'manufacturing' => null,
            'decoration_materials' => 27,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.5,
            'labor' => 7,
            'manufacturing' => null,
            'decoration_materials' => 9,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 4,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => 13,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.25,
            'labor' => 3,
            'manufacturing' => null,
            'decoration_materials' => 4,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.25,
            'labor' => 1.25,
            'manufacturing' => null,
            'decoration_materials' => 0.5,
            'subcontractors' => 1.5,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => 40,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 0.75,
            'manufacturing' => null,
            'decoration_materials' => 0.5,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 400,
        ],
        [
            'building_materials' => 1,
            'labor' => 8,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 6.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 4.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 6,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 6,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 2,
            'labor' => 120,
            'manufacturing' => null,
            'decoration_materials' => 150,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 130,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 15,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 35,
            'manufacturing' => null,
            'decoration_materials' => 120,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => 400,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 50,
            'manufacturing' => null,
            'decoration_materials' => 300,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => 200,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => 100,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => 300,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 20,
            'labor' => 120,
            'manufacturing' => null,
            'decoration_materials' => 250,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 20,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => 150,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 20,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => 250,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 10,
            'labor' => 110,
            'manufacturing' => null,
            'decoration_materials' => 400,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 30,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 40,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 20,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => 250,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 30,
            'labor' => 78,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 40,
            'labor' => 300,
            'manufacturing' => null,
            'decoration_materials' => 400,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => 5,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => 20,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => 80,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => 0.25,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 35,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => 45,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 5,
            'labor' => 25,
            'manufacturing' => null,
            'decoration_materials' => 25,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 10,
            'labor' => 50,
            'manufacturing' => null,
            'decoration_materials' => 100,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 10,
            'labor' => 50,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 10,
            'labor' => 65,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.1,
            'labor' => 0.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 0.8,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.4,
            'labor' => 1.25,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.4,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.1,
            'labor' => 0.35,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 0.6,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.4,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.4,
            'labor' => 0.9,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 4,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.15,
            'labor' => 0.25,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.45,
            'labor' => 0.65,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 0.4,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.15,
            'labor' => 0.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.5,
            'labor' => 0.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 2,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => 120,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => 150,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 100,
            'labor' => 45,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 250,
            'manufacturing' => null,
            'decoration_materials' => 350,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => 150,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => 150,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 20,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 20,
            'labor' => 70,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 5,
            'manufacturing' => null,
            'decoration_materials' => 30,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.6,
            'labor' => 0.8,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 4,
            'manufacturing' => null,
            'decoration_materials' => 3,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 3,
            'manufacturing' => null,
            'decoration_materials' => 3,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.2,
            'labor' => 1.2,
            'manufacturing' => null,
            'decoration_materials' => 1.8,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.15,
            'labor' => 1.85,
            'manufacturing' => null,
            'decoration_materials' => 1.25,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.25,
            'labor' => 3,
            'manufacturing' => null,
            'decoration_materials' => 2,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 2.8,
            'manufacturing' => null,
            'decoration_materials' => 1.7,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 3.5,
            'manufacturing' => null,
            'decoration_materials' => 1.7,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 8,
            'labor' => 70,
            'manufacturing' => null,
            'decoration_materials' => 30,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 60,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 40,
            'labor' => 50,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 5,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => 25,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 1,
            'labor' => 7,
            'manufacturing' => null,
            'decoration_materials' => 6,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => 1,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 62,
        ],
        [
            'building_materials' => 1,
            'labor' => 6,
            'manufacturing' => null,
            'decoration_materials' => 60,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 62,
        ],
        [
            'building_materials' => 1,
            'labor' => 7,
            'manufacturing' => null,
            'decoration_materials' => 10,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 8,
            'labor' => 30,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 8,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 8,
            'labor' => 25,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 8,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 8,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 8,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 1.7,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 1.3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 1,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 1.4,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 1.5,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 1.2,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 1.6,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.3,
            'labor' => 1.8,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 5,
            'labor' => 16,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 8,
            'labor' => 35,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 5,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 8,
            'labor' => 30,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 4,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 4,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 50,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 20,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 4,
            'labor' => 10,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 4,
            'labor' => 3,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => 120,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 20,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 120,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 300,
            'subcontractors' => 120,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 100,
            'subcontractors' => 50,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 1000,
            'subcontractors' => 400,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 800,
            'subcontractors' => 300,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 120,
            'subcontractors' => 50,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 800,
            'subcontractors' => 120,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 600,
            'subcontractors' => 120,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 300,
            'subcontractors' => 80,
        ],
        [
            'building_materials' => 20,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 25,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 200,
            'subcontractors' => 100,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 300,
            'subcontractors' => 120,
        ],
        [
            'building_materials' => 20,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 200,
            'subcontractors' => 120,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 900,
            'subcontractors' => 120,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 900,
            'subcontractors' => 90,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 1000,
            'subcontractors' => 150,
        ],
        [
            'building_materials' => null,
            'labor' => 200,
            'manufacturing' => null,
            'decoration_materials' => 700,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 120,
            'manufacturing' => null,
            'decoration_materials' => 450,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 400,
            'subcontractors' => 80,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 600,
            'subcontractors' => 120,
        ],
        [
            'building_materials' => null,
            'labor' => 180,
            'manufacturing' => null,
            'decoration_materials' => 1000,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => 200,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => 200,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 40,
            'manufacturing' => null,
            'decoration_materials' => 100,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => 30,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => 40,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 2,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => 50,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 50,
            'manufacturing' => null,
            'decoration_materials' => 100,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => 800,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 100,
            'manufacturing' => null,
            'decoration_materials' => 300,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 60,
            'manufacturing' => null,
            'decoration_materials' => 1000,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 65,
            'manufacturing' => null,
            'decoration_materials' => 300,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 800,
            'subcontractors' => 200,
        ],
        [
            'building_materials' => null,
            'labor' => 30,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 50,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 15,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 150,
            'manufacturing' => null,
            'decoration_materials' => 200,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 10,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => 300,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 120,
            'manufacturing' => null,
            'decoration_materials' => 500,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 120,
            'manufacturing' => null,
            'decoration_materials' => 500,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 10,
            'labor' => 80,
            'manufacturing' => null,
            'decoration_materials' => 300,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 100,
            'subcontractors' => 80,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 300,
            'subcontractors' => 150,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 20,
            'subcontractors' => 80,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 150,
            'subcontractors' => 100,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 95,
            'subcontractors' => 80,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 100,
            'subcontractors' => 100,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 100,
            'subcontractors' => 80,
        ],
        [
            'building_materials' => null,
            'labor' => 8,
            'manufacturing' => null,
            'decoration_materials' => 3,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => 8,
            'manufacturing' => null,
            'decoration_materials' => 3,
            'subcontractors' => null,
        ],
        [
            'building_materials' => 0.25,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 3,
            'subcontractors' => 4.5,
        ],
        [
            'building_materials' => 0.25,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 7,
            'subcontractors' => 5,
        ],
        [
            'building_materials' => 10,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => 200,
            'subcontractors' => 80,
        ],
        [
            'building_materials' => null,
            'labor' => 20,
            'manufacturing' => null,
            'decoration_materials' => 15,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 200,
        ],
        [
            'building_materials' => null,
            'labor' => 25,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => null,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 300,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 150,
        ],
        [
            'building_materials' => null,
            'labor' => null,
            'manufacturing' => null,
            'decoration_materials' => null,
            'subcontractors' => 1000,
        ],

    ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        for ($i = 0; $i < count($this->prices); $i++) {
            $this->prices[$i]['code_id'] = $i + 1;
        }
        DB::table('csi_code_prices')->insert(
            $this->prices
        );
    }
}
